# This workflow has been deprecated in favor of Vercel's automatic Git deployments
# Vercel automatically deploys on push to main branch
# To re-enable manual deployments via GitHub Actions:
# 1. Add VERCEL_TOKEN secret to repository secrets
# 2. Add VERCEL_ORG_ID secret to repository secrets
# 3. Add VERCEL_PROJECT_ID secret to repository secrets
# 4. Uncomment the workflow content below

# name: Deploy to Vercel
#
# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]
#
# env:
#   NODE_VERSION: '20'
#   VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
#   VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
#
# jobs:
#   # Quality checks are handled by deploy.yml workflow
#   # Vercel handles automatic deployments on git push
