name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  check-release-trigger:
    runs-on: ubuntu-latest
    outputs:
      should-release: ${{ steps.check.outputs.should-release }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check for release trigger
        id: check
        run: |
          # Check if the latest commit message contains a release trigger
          COMMIT_MSG=$(git log -1 --pretty=%B)
          if [[ "$COMMIT_MSG" =~ ^release:|^feat!:|BREAKING[[:space:]]CHANGE:|MINOR[[:space:]]RELEASE: ]]; then
            echo "should-release=true" >> $GITHUB_OUTPUT
            echo "Release triggered by: $COMMIT_MSG"
          else
            echo "should-release=false" >> $GITHUB_OUTPUT
            echo "No release trigger found in: $COMMIT_MSG"
          fi

  release-please:
    needs: check-release-trigger
    if: needs.check-release-trigger.outputs.should-release == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node

      # The logic below handles the npm version update and creates a PR
      - name: Checkout
        uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - name: Setup Node
        uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: '20'

      - name: Update npm dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: |
          npm ci

      # Output release information
      - name: Release Info
        if: ${{ steps.release.outputs.release_created }}
        run: |
          echo "Release created!"
          echo "Tag: ${{ steps.release.outputs.tag_name }}"
          echo "Version: ${{ steps.release.outputs.version }}"
          echo "Upload URL: ${{ steps.release.outputs.upload_url }}"
